repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-symlinks
    -   id: check-ast

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    -   id: ruff
        args: [--fix]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        types_or: [json5, json]
        additional_dependencies: ['prettier']

-   repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
    -   id: markdown-link-check
        args: ["--config", ".mlc_config.json"]

-   repo: local
    hooks:
      - id: mkdocs-build
        name: MkDocs Build
        entry: poetry run mkdocs build --strict
        language: python
        language_version: python3.11
        types: [markdown, yaml]
        pass_filenames: false
        always_run: true
        additional_dependencies: ['poetry>=1.7.1', 'mkdocs>=1.5.0', 'mkdocs-material>=9.0.0']
